### ISSUE TITLE
navigationview scrollviewer mouse wheel response area problem.

### ISSUE THREAD

**Issue by luckypong** [unoplatform/uno.templates#154]
### Current behavior

<img width="947" alt="navigationview" src="https://github.com/unoplatform/uno/assets/11326846/ca40beb1-3318-4888-b4e1-8ce703838c98">

It seems to respond when I scroll to an area of 50% of the screen size.

### Expected behavior

The left menu and the right content should be scrolled separately.

### How to reproduce it (as minimally and precisely as possible)

Add navigationview after creating uno project.
[UnoApp1.zip](https://github.com/unoplatform/uno/files/11642079/UnoApp1.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

<img width="296" alt="2023-06-03 170124" src="https://github.com/unoplatform/uno/assets/11326846/d630f982-0fb7-4c0f-af39-7201220c14f3">

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

17.6.2

**Comment by nickrandolph** [comment]
@luckypong can you confirm which version of the Wizard (the Uno Platform VS Extension) and/or Uno.Templates you're using to create the application. I've just tested with the latest [uno.templates](https://www.nuget.org/packages/uno.templates/4.9.9) and the Windows application does include the ApplicationManifest property in the first PropertyGroup inside the .Windows csproj file.

For anyone reading this issue, to reproduce the issue, the attached sample app needs to be run on a screen that doesn't have a scale factor of 100 in order to see the issue.

**Comment by luckypong** [comment]
@nickrandolph hmm. I remember it was 4.8 when the project was created.
And I created it with version 4.9 and checked the ApplicationManifest.
thank you.

**Comment by nickrandolph** [comment]
Marking this issue closed as not reproducible with latest template
