### ISSUE TITLE
Lottie references are transitive and are not aligned with Uno.Winui

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno.templates#284]
As discussed in https://github.com/unoplatform/uno/discussions/13619#discussioncomment-6996588, where the Uno.WinUI.Lottie package referenced by the app is too old, likely because toolkit and/or extensions references an earlier version (for a good reason).

We should be having the template referencing Uno.WinUI.Lottie, aligned with the version of the other `Uno.WinUI.*` packages, most likely only when we're adding toolkit and/or extensions to the app in the wizard.

**Comment by nickrandolph** [comment]
@jeromelaban are you suggesting that we attempt to lock Uno.WinUI.Lottie and Uno.WinUI.* to the same version (ie have a property in the Directory.Build.props that sets that version? Otherwise, we already have Lottie set to same version as Uno.WinUI.* (see https://github.com/unoplatform/uno.templates/blob/e2f55487de6fe4afb129d5dd091bc7bdddf8700f/src/Uno.Templates/content/unoapp/Directory.Packages.props#L123) so I'm not sure what the ask is here?

**Comment by jeromelaban** [comment]
I must have looked at the wrong place somehow, yes indeed it's set properly, thanks. Let's close.
