### ISSUE TITLE
[Uno.Template] init git when creating a new project

### ISSUE THREAD

**Issue by ajpinedam** [unoplatform/uno.templates#373]
### What would you like to be added

Validate if git is available, and if so, initialize the repository similar to Javascript project template solutions.

create-react-app
vite create-react

### Why is this needed

It improves the developer experience.

**Comment by dansiegel** [comment]
> Note that the template doesn't currently have `.gitignore`. This should be added as well

This is not actually true. We do not have it as part of source control however we actually pull the latest official .gitignore for Visual Studio when we package the templates and we add a couple of lines for the `solution-config.props` and we specifically allow including the publish profiles for the Windows head.

**Comment by ajpinedam** [comment]
> > Note that the template doesn't currently have `.gitignore`. This should be added as well
> 
> This is not actually true. We do not have it as part of source control however we actually pull the latest official .gitignore for Visual Studio when we package the templates and we add a couple of lines for the `solution-config.props` and we specifically allow including the publish profiles for the Windows head.

I was even thinking of using built-in dotnet utils to copy the `.gitignore` file `dotnet new gitignore`. Do you think that would work?

**Comment by dansiegel** [comment]
> I was even thinking of using built-in dotnet utils to copy the `.gitignore` file `dotnet new gitignore`. Do you think that would work?

@ajpinedam no that would not work. We have some additional things added to the .gitignore which is why we include it as part of the template already. As I said we pull it from the official [.gitignore for Visual Studio](https://github.com/github/gitignore/blob/main/VisualStudio.gitignore) file on GitHub each time we build the templates. This ensures that we stay up to date with what should be in the file while allowing us to make the modifications we need for the `solution-config.props` and the overrides to allow the publish profiles for the Windows head to be committed.

**Comment by dansiegel** [comment]
Closing this as it is not something that would lead to a good user experience. We would need to invoke 3 separate Post Actions:

- Init
- Stage
- Commit

This isn't likely to work at all from Visual Studio and would require the user by default to accept running each of the 3 post actions after every single template is created. Not to mention the nightmare this would cause our CI validation builds as it would be awaiting additional user input.

![image](https://github.com/unoplatform/uno.templates/assets/3860573/5d931543-7ca1-4e5c-8c78-063874aa59cc)
