### ISSUE TITLE
 'IHostBuilder' does not contain a definition for 'UseHttp'

### ISSUE THREAD

**Issue by jcropsey** [unoplatform/uno.templates#399]
### Current behavior

VS 2022 gives build error of "'IHostBuilder' does not contain a definition for 'UseHttp'" in the main project.

### Expected behavior

Project should build without any modifications.

### How to reproduce it (as minimally and precisely as possible)

Created a new Platform Uno app in VS 2022 Community Edition. In "Uno Platform Template Wizard", I selected Default and .NET 7. When I attempted to build the solution, it is giving an error of "'IHostBuilder' does not contain a definition for 'UseHttp'" in the main project.

### Works on UWP/WinUI

None

### Affected platforms

All

### IDE

Visual Studio 2022

**Comment by dansiegel** [comment]
Moving this to Templates as the problem from the attached project is that the Uno.Extensions.Http.WinUI package is missing for some reason...

@jcropsey when you created the attached project you just selected the Default with .NET 7? You didn't make any other changes? This is quite curious because while I can reproduce the issue you're seeing with the attached project I cannot reproduce the issue you're seeing from a new project and we naturally have integration tests that should prevent this sort of issue.

What's weirder is that you have the 2 serialization packages but are missing the `Uno.Extensions.Http.WinUI` package and that shouldn't be possible as these all come in as part of the same conditional block.
https://github.com/unoplatform/uno.templates/blob/71178aaa8601c86997e7d9460517755c68310485/src/Uno.Templates/content/unoapp/MyExtensionsApp._1/MyExtensionsApp._1.csproj#L57-L61

**Comment by jcropsey** [comment]
I tried this on a new computer, and it rendered correctly. I then tried update `uno-check`, but which claimed to update but without any output. I tried using `dotnet tool` commands to update as well as uninstall/reinstall but ran into issues where `dotnet tool` could not find `uno-check` to update/uninstall but could not install it either. At this point, I would attribute my bug as a problematic development machine and not something related to Platform Uno. Thanks for the help.
