### ISSUE TITLE
The Base project is confusing

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno.templates#422]
## What would you like to be added:

Seen today during Twitch stream - the user was confused about why there is a Base project among the platforms. He was thinking it is some baseline platform or Windows base

## Why is this needed:

The naming is maybe not clear, or the location should not be among Platforms.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

**Comment by jeromelaban** [comment]
The origin of this project is based in the fact that the app.xaml file cannot be placed in a separate library, for WinAppSDK.

Two options are possible:
- The base project, as it currently stands
- Using a "Shared" project type

It's was also useful to include platform specific like WebAssembly content, but since .NET 7, it's not useful anymore as the APIs used by the `Uno.Extensions.Logging.WebAssembly` are available for all targets (and does not need a `net8.0-webassembly` target framework).

We're also using it to place common content such as resizetizer and similar.

Considering the fact that `Uno.Extensions.Logging.WebAssembly` can be included for all targets, this part:
https://github.com/unoplatform/uno.templates/blob/414a74780cfb9766c9bbe4fdf1bb2c7274e14f18/src/Uno.Templates/content/unoapp/MyExtensionsApp._1.Base/AppHead.xaml.cs#L62

could be moved to be a runtime conditional inclusion through [`IsBrowser`](https://learn.microsoft.com/en-us/dotnet/api/system.operatingsystem.isbrowser?view=net-8.0). We could make most of this fake project empty, but we'd still have the `app.xaml` and `app.xaml.cs` appearing duplicate in all heads.

Using an SDK approach would remove the need for this hack, as the app.xaml would come back to the to main project, yet there are many aspects to consider to get to a fully working solution.

In the meantime, we could add a Readme file that points back at the documentation and explain what this project does.

**Comment by MartinZikmund** [comment]
I think a part of the confusion may stem from the fact that the project is in the Platforms solution folder - maybe having it outside could avoid the confusion of it being a target platform
