### ISSUE TITLE
`Uno.Resizetizer` package reference is only added for non-CPM projects.

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno.templates#76]
https://github.com/unoplatform/uno.templates/blob/f503e89b9cdc214438e9a4f008af2723a615b790/src/Uno.Templates/content/unoapp/MyExtensionsApp.1.Mobile/MyExtensionsApp.1.Mobile.csproj#L102-L104

When using CPM, the package reference doesn't seem to be there. The reference might not be necessary anyway because it's added to the class library project, but we should be consistent on whether to include it in Mobile.csproj or not.

**Comment by dansiegel** [comment]
actually I remember now... we always wanted it in base.props which works nicely with CPM because the NuGet Package Manager updates the Directory.Packages.props, but for non-CPM projects it needs to live in the project heads because the NuGet Package Manager updates all of the Project heads with a `<PackageReference Update` instead of updating the version in base.props.
